[workspace]
name = "pypetana"
version = "1.1.0"
description = "Petridish Image Extraction Tool and Dynamic Feature Analysis in Biological Systems"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.13.11,<3.14"
numpy = ">=2.4.1,<3"
pillow = ">=12.1.0,<13"
opencv = ">=4.12.0,<4.13.0"
threadpoolctl = ">=3.6.0,<4"
matplotlib = ">=3.10.8,<4"
black = "*"

[pypi-dependencies]
pypetana = { path = ".", editable = true }

[tasks]
run = "python -m pypetana"
